### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by ggHoek** [SimeonLukas/Bible-Crawler-Rust#1]
I'm a Windows user. Is there any chance to have some Spanish version, especially RVR1960? 

Thanks,

**Comment by SimeonLukas** [comment]
I try my Best.
But only these ones are available on the bibleserver.

![Screenshot_2023-03-08-12-34-58-967-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/33984591/223703219-cbdcc454-b992-4be1-adcb-658edca08566.jpg)


Greetings Simerl

**Comment by ggHoek** [comment]
Oh I see. Well, I think BTX works. Please let me know! Gracias!

**Comment by SimeonLukas** [comment]
Hithere

I added BTX.

Greetings,
Simerl
